pull_request_rules:
  - name: Dependency bumps merged on approval
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=Build check (ubuntu-latest, 14.x)
      - status-success=Run filter unit tests (ubuntu-latest, 14.x)
      - status-success=Run linting (ubuntu-latest, 14.x)
      - status-success=Run tests (ubuntu-latest, 14.x)
      - status-success=Run tests (ubuntu-latest, 14.x)
      - status-success=AccessLint
      - status-success=Header rules
      - status-success=Mixed content
      - status-success=Redirect rules
      - status-success=WIP
      - status-success=deploy/netlify
      - status-success=percy/inj.ms
    actions:
      merge:
        method: merge
