pull_request_rules:
  - name: Dependency bumps merged on approval
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=check-that-it-builds
      - status-success=linting
      - status-success=visual-regression-testing
      - status-success=visual-regression-testing
      - status-success=Header rules
      - status-success=Mixed content
      - status-success=Redirect rules
      - status-success=deploy/netlify
      - status-success=percy/inj.ms
    actions:
      merge:
        method: merge
