language: node_js
install:
  - npm install
  - wget -qO- 'https://cli.netlify.com/download/latest/linux' | tar xz
script:
  - npm run netlify
  - npm run percy
  # - npm run lighthouse -- $(./netlifyctl deploy --access-token $NETLIFY_AUTH_TOKEN --draft --yes | grep 'netlify.com')
  - npm run lighthouse
