language: node_js
addons:
  chrome: stable
install:
  - npm install
  - wget -qO- 'https://cli.netlify.com/download/latest/linux' | tar xz
script:
  - npm run netlify
  - bash ./run-percy-tests.sh
  - npm run lighthouse -- $(./netlifyctl deploy --access-token $NETLIFY_AUTH_TOKEN --draft --yes | grep 'netlify.com')
