[build]
    publish = "site"

[context.production.environment]
    NODE_ENV = "production"

[context.deploy-preview.environment]
    NODE_ENV = "production"

[Settings]
    ID = "248ac887-23bb-4560-8e03-7a3cb290350e"

# ------------------------------------------------------------------------------
# Headers
# ------------------------------------------------------------------------------

[[headers]]
    for = "/*"
    [headers.values]
        Content-Security-Policy = "default-src 'self' ; script-src 'self'; style-src 'unsafe-inline' ; img-src 'self' data: ; upgrade-insecure-requests; block-all-mixed-content;"
        Referrer-Policy = "strict-origin-when-cross-origin"
        X-Content-Type-Options = "nosniff"
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        Permissions-Policy = "interest-cohort=(), geolocation=(), gyroscope=(), microphone=(), camera=(), accelerometer=()"
        Link = "</assets/fonts/font.woff>; rel=preload; as=font; type=font/woff; crossorigin"

# ------------------------------------------------------------------------------
# Shortlinks
# ------------------------------------------------------------------------------
[[redirects]]
    from = "/inceptionhorn"
    to = "https://inception.davepedu.com/"
    status = 302

[[redirects]]
    from = "/poplb"
    to = "https://iso.500px.com/50-photos-of-pandas-looking-bored"
    status = 302

[[redirects]]
    from = "/quokkaselfie"
    to = "http://news.nationalgeographic.com/news/2015/03/150306-quokkas-selfies-animals-science-photography-australia/"
    status = 302

[[redirects]]
    from = "/iubenda"
    to = "https://github.com/injms/iubenda-for-wp"
    status = 302

[[redirects]]
    from = "/cisfas"
    to = "https://www.theguardian.com/commentisfree/2002/nov/29/1"
    status = 302

[[redirects]]
    from = "/tbpsit"
    to = "http://www.boston.com/bigpicture/2014/04/survival_in_the_amazon.html"
    status = 302

[[redirects]]
    from = "/tmtayn"
    to = "http://edition.cnn.com/interactive/2014/04/opinion/sutter-change-the-list-pangolin-trafficking/"
    status = 302

[[redirects]]
    from = "/ipoie6"
    to = "http://www.brucelawson.co.uk/2010/in-praise-of-ie6/"
    status = 302

[[redirects]]
    from = "/ngpwsb"
    to = "http://news.nationalgeographic.com/news/2014/03/140302-pebble-mine-bristol-bay-alaska-epa-environment/"
    status = 302

[[redirects]]
    from = "/rick"
    to = "https://youtu.be/dQw4w9WgXcQ"
    status = 302

[[redirects]]
    from = "/photography"
    to = "https://www.ianjamesphotography.com/photos"
    status = 302

[[redirects]]
    from = "/photos"
    to = "https://www.ianjamesphotography.com/photos"
    status = 302

[[redirects]]
    from = "/linkedin"
    to = "https://www.linkedin.com/in/injms/"
    status = 302

[[redirects]]
    from = "/instagram"
    to = "https://instagram.com/inj.ms"
    status = 302

[[redirects]]
    from = "/github"
    to = "https://github.com/injms"
    status = 302

[[redirects]]
    from = "/copyright"
    to = "https://www.ianjamesphotography.com/copyright"
    status = 302

[[redirects]]
    from = "/lighthouse-and-comment"
    to = "https://github.com/injms/lighthouse-and-comment-action/#readme"
    status = 302
