name: Check if builds okay

on:
 - push

jobs:
  check-that-it-builds:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.1.4
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm run build
