name: Check if builds okay

on: [push]

jobs:
  build:
    name: Build check
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [ubuntu-latest]
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm ci
    - name: build
      run: npm run build
    - name: save built site
      uses: actions/upload-artifact@v1
      with:
        name: built-site
        path: site
      env:
        CI: true
