name: Lighthouse audit

on: pull_request

jobs:
  lighthouse-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Lighthouse audits
        uses: injms/lighthouse-and-comment-action@primary
        with:
          live_url: "https://inj.ms"
          pr_url_pattern: "https://deploy-preview-{{PULL_REQUEST_NUMBER}}--injms.netlify.app"
          pages: '["/"]'
          github_token: ${{ secrets.GITHUB_TOKEN }}
