name: Linting

on:
 - push

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.1.2
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm run lint
