# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the primary branch
on: pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        path: main
        ref: primary
        
    - uses: actions/checkout@v2
      with:
        path: pull_request
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        ls -la
        cd main
        ls -la
        cd ../pull_request
        ls -la
