name: Visual regression test

on:
  push:
    branches:
      - primary
  pull_request:

jobs:
  visual-regression-testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: percy/snapshot-action@v0.1.2
      with:
        build-directory: "site/"
      env:
        PERCY_TOKEN: "${{ secrets.PERCY_TOKEN }}"
