name: Visual regression test

on:
 - pull_request
 - push

jobs:
  visual-regression-testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.1.4
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm run build
    - uses: percy/snapshot-action@v0.1.2
      with:
        build-directory: "site/"
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}