name: Visual regression test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  visual-regression-testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npx @percy/cli snapshot site/
      env:
        PERCY_TOKEN: "${{ secrets.PERCY_TOKEN }}"
