name: Visual regression test

on: [pull_request]

jobs:
  build:
    name: Build check
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [ubuntu-latest]
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm ci
    - name: build
      run: npm run build
    - name: percy
      uses: percy/snapshot-action@v0.1.0
      with:
        build-directory: "site/"
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}